print("This is an atbash cipher program.")
print("")
clear_text = input("Enter your text:")
clear_text= clear_text.upper()
print("")


cipher_text = clear_text.replace("A","z")
cipher_text = cipher_text.replace("B","y")
cipher_text = cipher_text.replace("C","x")
cipher_text = cipher_text.replace("D","w")
cipher_text = cipher_text.replace("E","v")
cipher_text = cipher_text.replace("F","u")
cipher_text = cipher_text.replace("G","t")
cipher_text = cipher_text.replace("H","s")
cipher_text = cipher_text.replace("I","r")
cipher_text = cipher_text.replace("J","q")
cipher_text = cipher_text.replace("K","p")
cipher_text = cipher_text.replace("L","o")
cipher_text = cipher_text.replace("M","n")
cipher_text = cipher_text.replace("N","m")
cipher_text = cipher_text.replace("O","l")
cipher_text = cipher_text.replace("P","k")
cipher_text = cipher_text.replace("Q","j")
cipher_text = cipher_text.replace("R","i")
cipher_text = cipher_text.replace("S","h")
cipher_text = cipher_text.replace("T","g")
cipher_text = cipher_text.replace("U","f")
cipher_text = cipher_text.replace("V","e")
cipher_text = cipher_text.replace("W","d")
cipher_text = cipher_text.replace("X","c")
cipher_text = cipher_text.replace("Y","b")
cipher_text = cipher_text.replace("Z","a")

cipher_text = cipher_text.title()
cipher_text = cipher_text.swapcase()

print(cipher_text)