print("")
print("Cryptography")
input("Press enter to continue.")
print("")
print("    The practice of creating codes to keep information secret. This works by converting data into an unreadable format that allows it to be shared without any unauthorized person decoding it into a readable format. In order to decrypt the code, you need a key to cipher it.")
input("Press enter to continue.")
print("")
print("   Cryptography is often used in informatio security to keep private data safe. Th information is not permanently changed during transmission or while being stored. When an authorized user views the data and decrypts it, they will see exactly the same files they originally encrypted.")
input("Press enter to continue.")
print("")
print("There are three basic types of cryptography.")
input("Press enter to continue.")
print("")
print("    Secret key encryption uses one key that is used to encrypt and decrypt the data.")
input("Press enter to continue.")
print("")
print("    Public key encryption uses two keys, one that is private and one that is public. The sender uses the public key that everyone can see to encrypt the data and the receiver uses a private key to decrypt it.")
input("Press enter to continue.")
print("")
print("    The last type of cryptography is called a hash function. Hash functions are mainly used to store files. There are no keys used, and the file is unrecoverable from the encryption, or, in other words, you can't decrypt it.")
input("Press enter to continue.")
print("")
print("    The source used to obtain this information was https://www.techopedia.com/definition/1770/cryptography")
print("")
 